In [60]:
import sys, os
import torch
import numpy as np
import json
import datetime

from dynamics.process.rnn import parse

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [61]:
savedir = '/Users/dhocker/projects/kind_cl/data/rnndata_matlab/overtraining/'
datadir = '/Users/dhocker/projects/dynamics/results/20231003/full_cl/'

In [50]:
num = 26
#name = 'rnn_'+str(num)+'_allbeh_1k.json'
fname = 'rnn_'+str(num)+'_allbeh.json'
with open(datadir+fname,'rb') as f:
    dat = json.load(f)
    

In [71]:
#iterate over numbers
use1k = False

for num in range(1,51):

    
    print(num)
    if use1k:
        fname = 'rnn_'+str(num)+'_allbeh_1k.json'
    else:
        fname = 'rnn_'+str(num)+'_allbeh.json'
    
    with open(datadir+fname,'rb') as f:
        dat = json.load(f)

    #find block sessions 
    idxlist = []
    blocklist = []
    for k in range(len(dat)):
        if dat[k]['name'].find('block') > 0:
            blocklist.append(k)
            if use1k:
                # if 1k.json
                idxlist.append(int(dat[k]['name'].split('_')[-2]))
            else:
                # if 1k.json
                idxlist.append(int(dat[k]['name'].split('_')[-1].strip('.json')))


    blocklist = np.array(blocklist)[np.argsort(np.array(idxlist))]



    # break into similar-sized seddioss, then aggreate back to big session
    datlist_main = []
    tokeep_main = []
    ntrials_main = []

    for j in blocklist:

        datlist, tokeep = parse.format2sess(dat[j], useblocks=True, blockspersess=5)
        ntrials = [len(k['rewvols']) for k in datlist]
        ntrials_2 = [len(k['outcomes']) for k in datlist]
        ntrials_3 = [len(k['blocks']) for k in datlist]
        
        for m in range(len(datlist)):
            datlist_main.append(datlist[m])
            tokeep_main.append(tokeep[m])
            if tokeep[m]:
                ntrials_main.append(ntrials[m])

    #aggregate into large session
    dat_test = parse.format2singlesess(datlist_main, tokeep_main)
    


    # save as matlab file
    if use1k:
        savename = savedir+'rnn_'+str(num)+'_allbeh_1k.mat'
    else:
        savename = savedir+'rnn_'+str(num)+'_allbeh.mat'

    A = parse.generate_rattrial_rnn(dat_test, savename,
                              date_base=str(datetime.date.today())+' ', ops=None, ntrials=ntrials_main)

1


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
2


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
3


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if 

supplied data, not filename. using data directroy
4


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
5


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
6


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if 

supplied data, not filename. using data directroy
7


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if 

supplied data, not filename. using data directroy
8
supplied data, not filename. using data directroy
9


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if 

supplied data, not filename. using data directroy
10
supplied data, not filename. using data directroy
11


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
12


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if 

supplied data, not filename. using data directroy
13


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Pr

supplied data, not filename. using data directroy
14


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if 

supplied data, not filename. using data directroy
15


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
16


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
17
supplied data, not filename. using data directroy
18


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if 

supplied data, not filename. using data directroy
19
supplied data, not filename. using data directroy
20


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
21


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Pr

[30.1 30.1 30.1 30.1 30.1 30.1]


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurtosis = 3 + stats.kurtosis(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/st

/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurtosis = 3 + stats.kurtosis(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1606: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  b2 = skew(a, axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packag

[30.1 30.1 30.1 30.1 30.1 30.1]


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurtosis = 3 + stats.kurtosis(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1606: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  b2 = skew(a, axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packag

supplied data, not filename. using data directroy
22


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
23
supplied data, not filename. using data directroy
24
supplied data, not filename. using data directroy
25
supplied data, not filename. using data directroy
26


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
27


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
28


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
29
supplied data, not filename. using data directroy
30


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
31


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
32
supplied data, not filename. using data directroy
33
supplied data, not filename. using data directroy
34


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
35


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
36


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
37
supplied data, not filename. using data directroy
38


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
39


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
40


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
41


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
42


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if 

supplied data, not filename. using data directroy
43


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
44


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_morestats.py:4088: UserWarning: Exact p-value calculation does not work if there are zeros. Switching to normal approximation.
  warnings.warn("Exact p-value calculation does not work if there are "


supplied data, not filename. using data directroy
45


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurtosis = 3 + stats.kurtosis(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1606: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  b2 = skew(a, axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packag

[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurtosis = 3 + stats.kurtosis(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1606: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  b2 = skew(a, axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packag

[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurtosis = 3 + stats.kurtosis(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1606: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  b2 = skew(a, axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packag

[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurtosis = 3 + stats.kurtosis(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1606: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  b2 = skew(a, axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packag

[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurtosis = 3 + stats.kurtosis(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1606: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  b2 = skew(a, axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packag

[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurtosis = 3 + stats.kurtosis(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1606: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  b2 = skew(a, axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packag

[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurtosis = 3 + stats.kurtosis(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1606: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  b2 = skew(a, axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packag

[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]
[30.1 30.1 30.1 30.1 30.1 30.1]
supplied data, not filename. using data directroy
46


/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:125: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  skew = stats.skew(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/statsmodels/stats/stattools.py:126: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  kurtosis = 3 + stats.kurtosis(resids, axis=axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packages/scipy/stats/_stats_py.py:1606: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  b2 = skew(a, axis)
/Users/dhocker/miniconda3/envs/torchenv/lib/python3.11/site-packag

supplied data, not filename. using data directroy
47
supplied data, not filename. using data directroy
48
supplied data, not filename. using data directroy
49
supplied data, not filename. using data directroy
50
supplied data, not filename. using data directroy


In [10]:
type(datlist)

list

In [8]:
dat_test

dict